# site properties and page defaults
title: CVRLAB
subtitle: Computer Vision Research Lab
description: Image has become convenient input to most of the applications in the industries and real life. Vision applications like robotic motion, conveyor belt application, automatic vehicle control, video surveillance, automatic quality control, biometrics etc. use image(s) as input. The extracted patterns from the images serve as the major factor deciding the quality of output in the said applications. Hence computer vision and pattern recognition has emerged as an important field of research and prerequisite of many application specific processes. The center will thrust upon researching out industry oriented outputs in the field of computer vision and pattern recognition, and will further step ahead for integrating the developed methods with real world applications.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@computervisionresearchlab.com
  orcid: 0000-0001-8713-9213
  google-scholar: uZD3PU4AAAAJ
  github: computervisionresearchlab
  twitter: cvrlab_x
  youtube: ComputerVisionResearchLab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
